Add support for host option
sindresorhus/pid-port pull request #6
Opened 2020-12-29 15:03 UTC by nagygergo

Fixes #3. 

TODO: Update `.all()`

How should the `.all()` method be supported? 
My proposal would be that `.all()` returns a `{port}-{pid}` map for all the hosts and `.all(host)` `{port}-{pid}` map for the given host.

TODO: Update Readme with examples

2020-12-29 17:43 UTC, sindresorhus requested changes

2020-12-29 17:43 UTC, sindresorhus commented on index.js
> +module.exports.portToPid = async (arg1, arg2) => {
`host` should be an option in an options-object.

2020-12-29 17:43 UTC, sindresorhus commented on test.js
> +test('Node `server.listen()` signature - with different host as arg', async t => {
Don't use abbreviations.

2020-12-29 17:43 UTC, sindresorhus commented on index.js
> +		port = arg1;
Don't use abbreviations.

2020-12-29 17:46 UTC, sindresorhus commented
> My proposal would be that .all() returns a {port}-{pid} map for all the hosts and .all(host) {port}-{pid} map for the given host.

I think it needs to include the host too. So maybe: `Promise<Map<number, {host: number, port: number}>>`. And yes, it should have a `host` option.

2020-12-29 17:46 UTC, sindresorhus commented on index.js
> +const getPort = (port, list, host) => {
```suggestion
const getPort = (host, port, list) => {
```

2020-12-29 17:47 UTC, sindresorhus commented
And `host` should have a default.

2021-01-02 21:07 UTC, nagygergo commented
> > My proposal would be that .all() returns a {port}-{pid} map for all the hosts and .all(host) {port}-{pid} map for the given host.
> 
> I think it needs to include the host too. So maybe: `Promise<Map<number, {host: number, port: number}>>`. And yes, it should have a `host` option.

I don't think `Promise<Map<number, {host: number, port: number}>>` would work, becuase a single pid could have multiple ports associated to it. So I think the `Promise<Map<number,number>` with pid-port map is ok.

2021-01-02 21:09 UTC, nagygergo commented on index.js
> +module.exports.portToPid = async (arg1, arg2) => {
The `net.server.listen(port, host)` signature is valid, but leaving that out is fine for me.

2021-01-02 21:13 UTC, nagygergo commented
> And `host` should have a default.

My understanding is that if the host is not specified the mapping between the port and the pid  should be done for all the local addresses that executing machine owns, like 127.0.0.1, 192.168.8.8, maybe a non-local subnet IP.

I don't know what would be a good default for scanning.

2021-01-04 03:04 UTC, sindresorhus commented
> I don't think Promise<Map<number, {host: number, port: number}>> would work, becuase a single pid could have multiple ports associated to it. So I think the Promise<Map<number,number> with pid-port map is ok.

Just a typo. I meant: `Promise<Map<number, {host: string, pid: number}>>`

2021-01-04 03:07 UTC, sindresorhus commented
> My understanding is that if the host is not specified the mapping between the port and the pid should be done for all the local addresses that executing machine owns, like 127.0.0.1, 192.168.8.8, maybe a non-local subnet IP.
> I don't know what would be a good default for scanning.

That makes sense to me. The behavior needs to be documented though.

@silverwind Thoughts on this?

2021-01-10 13:26 UTC, sindresorhus commented
// @Richienb In case you're interested in helping reviewing this.

2021-01-10 14:14 UTC, nagygergo commented
Hey @Richienb, @sindresorhus. 

Just going through some edge-cases for the host-port-pid mapping, the issue is that it's a many-to-many-to-many mapping. The current api signatures do not really cater for these cases. So in the following cases the current methods have unspecified behavior:

1. A machine is using multiple local addresses , but has a processes occupying the same port (127.0.0.1:1212, 127.0.0.2:1212).  (this can easily happen when virtualization agent is creating virtual networks for it's VMs, like KVM or Minikube)
2. A machine is running a cluster of workers to process the same port, in this case there are many pids associated to the same host:port combination (eg. httpd)
```
Netid  State      Recv-Q Send-Q Local Address:Port     Peer Address:Port
tcp    LISTEN     0      128    :::80                :::*                 users:(("httpd",pid=10522,fd=4),("httpd",pid=10521,fd=4),("httpd",pid=10520,fd=4),("httpd",pid=10519,fd=4),("httpd",pid=10518,fd=4),("httpd",pid=10516,fd=4))
```
3. A process is consuming more than 1 port or more than 1 port across different local addresses. (I don't know a good example to this)

Not sure about the exact solution yet, will think about it next week, and I'm not sure if there is a need to handle these kinds of usecases, but I wanted to point them out anyways.

2021-01-11 12:27 UTC, silverwind commented
> My understanding is that if the host is not specified the mapping between the port and the pid should be done for all the local addresses that executing machine owns, like 127.0.0.1, 192.168.8.8, maybe a non-local subnet IP.
I don't know what would be a good default for scanning.

From [node docs](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback):

> If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.

Unspecified IPv6 address means dual-stack behaviour so it will match all local IPv4 and IPv6 interface when IPv6 is available (not sure how to check), so I think it's fine for this module to return all PIDs that listen on the specified port, IPv4 and IPv6.

2021-03-07 08:29 UTC, sindresorhus commented
@nagygergo Still interested in finishing this PR? 🙏

2021-08-20 23:42 UTC, sindresorhus commented
Bump :)

2021-10-04 06:49 UTC, closed without merging